server:
  port: 5500
spring:
  cloud:
    config:
     server:
      git:
        uri: https://gitee.com/zhouweitong1997/zhou-config.git
        search-paths: config
        username: zhouweitong1997
        password: 1997217zou
security:
  basic:
    enabled: true
  user:
    password: 123456
    name: root