server:
  port: 3500
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7777/eureka
zuul:
  routes:
    zwt-eureka-consumer: /zhou/**
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
ribbon:
  ReadTimeout: 12000
  ConnectionTimeout: 1000
management:
  security:
    enabled: false


