spring:
  profiles: p1
server:
  port: 8888
---
spring:
  profiles: p2
server:
  port: 8889
---
spring:-
  application:
    name: blog-eureka-provider
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1997217zou
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@peer1:7777/eureka
mybatis:
  type-aliases-package: com.zhou.bean
  mapper-locations: classpath:mapper/*Mapper.xml