
server:
  port: 9999
spring:
  application:
    name: zwt-eureka-consumer
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@peer1:7777/eureka
feign:
  hystrix:
    enabled: true

dm-user-provider:
  ribbon:
    NFloadBalanceRuleClassName: com.netflix.loadbalancer.BestAvailableRule