spring:
 profiles: zhou1
server:
  port: 7777
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7778/eureka
---
spring:
 profiles: zhou2
server:
  port: 7778
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7777/eureka
---
spring:
  application:
    name: zwt-eureka-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  server:
    enable-self-preservation: false
security:
  user:
    name: root
    password: 123456
  basic:
    enabled: true
