server:
  port: 8888
spring:
  profiles: p1
---
server:
  port: 8889
spring:
  profiles: p2
---
spring:
  application:
    name: zwt-eureka-provider
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@peer1:7777/eureka
