server:
  port: 8888
spring:
  application:
    name: products-eureka-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: 1997217zou
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@peer1:7777/eureka
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zhou.bean