server:
  port: 9999
spring:
  application:
    name: blog-eureka-consumer
  redis:
    database: 0
    host: 192.168.233.128
    port: 6379
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@peer1:7777/eureka
feign:
  hystrix:
    enabled: true
blog-erurka-provider:
  ribbon:
    NFloadBalanceRuleClassName: com.netflix.loadbalancer.BestAvailableRule
